easy_admin:
    list:
        actions: ['search', 'delete', 'show']
    entities:
        JoindInEvent:
            class: App\Entity\JoindInEvent
        JoindInTalk:
            class: App\Entity\JoindInTalk
        JoindInComment:
            class: App\Entity\JoindInComment
        JoindInUser:
            class: App\Entity\JoindInUser
        Raffle:
            class: App\Entity\Raffle
            disabled_actions: ['new']
            edit:
                fields:
                    - events
                    - winners
                    - noShows

