homepage:
    path: /
    defaults: { _controller: 'App\Controller\HomepageController::index' }

raffle_web_homepage:
    path: /web/
    defaults: { _controller: 'App\Controller\RaffleWebController::index' }

raffle_web_start:
    path: /web/raffle/start
    methods: [POST]
    defaults: { _controller: 'App\Controller\RaffleWebController::start' }

raffle_web_show:
    path: /web/raffle/{id}
    defaults: { _controller: 'App\Controller\RaffleWebController::show' }

raffle_web_pick:
    path: /web/raffle/{id}/pick
    methods: [POST]
    defaults: { _controller: 'App\Controller\RaffleWebController::pick' }

raffle_web_winner:
    path: /web/raffle/{id}/winner/{userId}
    methods: [POST]
    defaults: { _controller: 'App\Controller\RaffleWebController::winner' }

raffle_web_noshow:
    path: /web/raffle/{id}/no_show/{userId}
    methods: [POST]
    defaults: { _controller: 'App\Controller\RaffleWebController::noShow' }

joindin_events_fetch:
    path: /api/joindin/events/fetch
    defaults: { _controller: 'App\Controller\JoindInEventController::fetch' }


joindin_events_list:
    path: /api/joindin/events/
    defaults: { _controller: 'App\Controller\JoindInEventController::eventList' }


talks_fetch:
    path: /api/joindin/talks/fetch
    defaults: { _controller: 'App\Controller\JoindInTalkController::fetch' }


talks_list:
    path: /api/joindin/talks/
    defaults: { _controller: 'App\Controller\JoindInTalkController::talkList' }


comments_fetch:
    path: /api/joindin/comments/fetch
    defaults: { _controller: 'App\Controller\JoindInCommentController::fetch' }


comments_list:
    path: /api/joindin/comments/
    defaults: { _controller: 'App\Controller\JoindInCommentController::commentList' }


raffle_api_start:
    path: /api/raffle/start
    methods: [POST]
    defaults: { _controller: 'App\Controller\RaffleApiController::start' }


raffle_api_pick:
    path: /api/raffle/{id}/pick
    methods: [POST]
    defaults: { _controller: 'App\Controller\RaffleApiController::pick' }

raffle_api_winner:
    path: /api/raffle/{id}/winner/{userId}
    methods: [POST]
    defaults: { _controller: 'App\Controller\RaffleApiController::winner' }

raffle_api_no_show:
    path: /api/raffle/{id}/no_show/{userId}
    methods: [POST]
    defaults: { _controller: 'App\Controller\RaffleApiController::noShow' }


raffle_api_show:
    path: /api/raffle/{id}
    defaults: { _controller: 'App\Controller\RaffleApiController::show' }

raffle_api_comments:
    path: /api/raffle/{id}/comments
    defaults: { _controller: 'App\Controller\RaffleApiController::comments' }


# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
