homepage:
    path: /
    defaults: { _controller: 'App\Controller\HomepageController::index' }

joindin_events_fetch:
    path: /joindin/events/fetch
    defaults: { _controller: 'App\Controller\JoindInEventController::fetch' }


joindin_events_list:
    path: /joindin/events/
    defaults: { _controller: 'App\Controller\JoindInEventController::eventList' }


talks_fetch:
    path: /joindin/talks/fetch
    defaults: { _controller: 'App\Controller\JoindInTalkController::fetch' }


talks_list:
    path: /joindin/talks/
    defaults: { _controller: 'App\Controller\JoindInTalkController::talkList' }


comments_fetch:
    path: /joindin/comments/fetch
    defaults: { _controller: 'App\Controller\JoindInCommentController::fetch' }


comments_list:
    path: /joindin/comments/
    defaults: { _controller: 'App\Controller\JoindInCommentController::commentList' }



# first, run composer req annotations
#controllers:
#    resource: ../src/Controller/
#    type: annotation
